### ISSUE TITLE
Failed on Node.js 4 (travis)

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/eslint-config-i-am-meticulous#110]
> ESLint couldn't find the plugin "eslint-plugin-import".

See https://travis-ci.org/postcss/postcss-custom-media/jobs/231478799

**Comment by MoOx** [comment]
npm2 I guess?

**Comment by Semigradsky** [comment]
Yeah

**Comment by MoOx** [comment]
so add "eslint-plugin-import" as a dep, should do the trick

**Comment by Semigradsky** [comment]
That helped
