### ISSUE TITLE
Switch to eslint 6.x ?

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/eslint-config-i-am-meticulous#116]

**Comment by MoOx** [comment]
PR welcome :)

**Comment by Semigradsky** [comment]
Ok, I will )

**Comment by Semigradsky** [comment]
Publish new version? :)

**Comment by MoOx** [comment]
12.0.0 is out. I had to handle a thing to prevent warning first (if you are curious... https://github.com/MoOx/github-release-from-changelog/commit/13ece121ed91f4cdf330e20b2b3c56eccf47f0c5)
